#!/bin/bash

gamedir='$HOME/rpgBashGame'

#cd $HOME/rpgBashGame

export PS1='Claud@Masria:'

clear
echo " "
read -p "Pulsa la tecla [INTRO] para continuar la aventura donde te quedaste!" abc


if [[ $(uname) == "Darwin" ]]
then

	#PATH MAC OS X
	PATH=$PATH:$HOME/bin
	open $HOME/rpgBashGame/caratula.png &
fi

if [[ -f /usr/bin/eog ]]
then eog $HOME/rpgBashGame/caratula.png &
fi

if [[ -f /usr/bin/eom ]]
then eom $HOME/rpgBashGame/caratula.png &
fi


ubicacion=$(cat $HOME/rpgBashGame/saved_game)

move $ubicacion
