#!/bin/bash

gamedir='$HOME/rpgBashGame'

rm -rf $HOME/rpgBashGame/Masria
mkdir -p $HOME/rpgBashGame
cd $HOME/rpgBashGame
tar -xzvf $HOME/rpgBashGame/Masria.tar.gz
echo "$HOME/rpgBashGame/Masria" > $HOME/rpgBashGame/saved_game

Mochila=''
rm $HOME/rpgBashGame/Masria/home/Mochila/*
touch $HOME/rpgBashGame/Masria/home/Mochila/monedas
echo "100" > $HOME/rpgBashGame/Masria/home/Mochila/monedas


export PS1='Claud@Masria:'

clear
cat Masria/.scene
echo " "
read -p "Pulsa la tecla [INTRO] para empezar la aventura!" abc


if [[ $(uname) == "Darwin" ]]
then

#PATH MAC OS X
PATH=$PATH:$HOME/bin
open $HOME/rpgBashGame/caratula.png &
fi

if [[ -f /usr/bin/eog ]]
then eog $HOME/rpgBashGame/caratula.png &
fi

if [[ -f /usr/bin/eom ]]
then eom $HOME/rpgBashGame/caratula.png &
fi



move $HOME/rpgBashGame/Masria
